export const mockData = Array.from({ length: 10 }, (_, index) => ({
  index: index + 1,
  화주사: `택배사 ${index + 1}`,
  회차명: `택배사 ${index + 1}에 사용되는 라우트 입니다.`,
  요청일시: `24-07-${Math.floor(Math.random() * 30) + 1} / 15:00`,
  요청상세: index,
  회수요청상태: index + 1,
}));

export const FilterMockData = [
  {
    sortation: 'LDV',
    index: 1,
    id: '아이디1',
    company: '롯데택배',
  },
  {
    sortation: '1T',
    index: 2,
    id: '아이디2',
    company: '롯데택배',
  },
  {
    sortation: 'LDV',
    index: 3,
    id: '아이디3',
    company: '한진택배',
  },
  {
    sortation: 'LDV',
    index: 4,
    id: '아이디4',
    company: '한진택배',
  },
  {
    sortation: '1T',
    index: 5,
    id: '아이디5',
    company: '우체국택배',
  },
  {
    sortation: 'LDV',
    index: 6,
    id: '아이디6',
    company: '로젠택배',
  },
  {
    sortation: '1T',
    index: 7,
    id: '아이디7',
    company: '드림택배',
  },
  {
    sortation: '1T',
    index: 8,
    id: '아이디7',
    company: '대신택배',
  },
  {
    sortation: 'LDV',
    index: 9,
    id: '아이디7',
    company: '일양로지스',
  },
  {
    sortation: '1T',
    index: 10,
    id: '아이디7',
    company: '경동택배',
  },
];

export const recoveryDetailMockData = [
  {
    index: 1,
    waybill: 12309845012804,
    sortation: '프레시백',
    address: '경상북도 김천시 혁신6로 10, 203호',
    address2: '경상북도 김천시 율곡동 1234, 203호',
    route: 'P1 - 1',
    driver: '오석중',
    customer_info: '',
    modify: '',
    delete: '',
  },
  {
    index: 2,
    waybill: 12309845012804,
    sortation: '프레시백',
    address: '경상북도 김천시 혁신6로 10, 203호',
    address2: '경상북도 김천시 율곡동 1234, 203호',
    route: 'P1 - 1',
    driver: '오석중',
    customer_info: 'detail',
    modify: 'modify',
    delete: 'delete',
  },
  {
    index: 3,
    waybill: 12309845012804,
    sortation: '프레시백',
    address: '경상북도 김천시 혁신6로 10, 203호',
    address2: '경상북도 김천시 율곡동 1234, 203호',
    route: 'P1 - 1',
    driver: '오석중',
    customer_info: '',
    modify: '',
    delete: '',
  },
  {
    index: 4,
    waybill: 12309845012804,
    sortation: '프레시백',
    address: '경상북도 김천시 혁신6로 10, 203호',
    address2: '경상북도 김천시 율곡동 1234, 203호',
    route: 'P1 - 1',
    driver: '오석중',
    customer_info: '',
    modify: '',
    delete: '',
  },
  {
    index: 5,
    waybill: 12309845012804,
    sortation: '프레시백',
    address: '경상북도 김천시 혁신6로 10, 203호',
    address2: '경상북도 김천시 율곡동 1234, 203호',
    route: 'P1 - 1',
    driver: '오석중',
    customer_info: '',
    modify: '',
    delete: '',
  },
];
export const recoveryDispatchMockData = [{
  routeName: 'P1 - a',
  addressStandard: '50',
  productStandard: '100',
  deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
}, {
  routeName: 'P2 - b',
  addressStandard: '60',
  productStandard: '200',
  deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
},
  {
    routeName: 'P2 - b',
    addressStandard: '60',
    productStandard: '200',
    deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
  },
  {
    routeName: 'P2 - b',
    addressStandard: '60',
    productStandard: '200',
    deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
  },
  {
    routeName: 'P2 - b',
    addressStandard: '60',
    productStandard: '200',
    deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
  },
  {
    routeName: 'P2 - b',
    addressStandard: '60',
    productStandard: '200',
    deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
  },
  {
    routeName: 'P2 - b',
    addressStandard: '60',
    productStandard: '200',
    deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
  },
  {
    routeName: 'P2 - b',
    addressStandard: '60',
    productStandard: '200',
    deliveryDrivers: ['배송기사1', '배송기사2', '배송기사3'],
  },
];
