import { BUTTON_TEXT, SELECT_OPTION } from '../constants/text';

export const SELECT_OPTIONS = {
  // 배송 요청 상태 옵션
  DELIVERY_STATUS: [
    SELECT_OPTION.DEFAULT,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.REQUEST,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.DISPATCH,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.SORTING_SCAN,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.SORTING_SCAN_PROGRESSING,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.PICKUP_SCAN,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.DELIVERY,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.COMPLETE,
  ],

  SMS_DELIVERY_STATUS: [
    SELECT_OPTION.DEFAULT,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.REQUEST,
    BUTTON_TEXT.STATUS.DELIVERY_REQUEST.CLOSE,
  ],

  SORTING_STATUS: [
    SELECT_OPTION.DEFAULT,
    BUTTON_TEXT.STATUS.SORTING_REQUEST.WATING,
    BUTTON_TEXT.STATUS.SORTING_REQUEST.IN_SORTING,
    BUTTON_TEXT.STATUS.SORTING_REQUEST.COMPLETE,
  ],

  RECALL_STATUS: [
    SELECT_OPTION.DEFAULT,
    BUTTON_TEXT.STATUS.RECOVERY_REQUEST.REQUEST,
    BUTTON_TEXT.STATUS.RECOVERY_REQUEST.DISPATCH,
    BUTTON_TEXT.STATUS.RECOVERY_REQUEST.RECOVERY,
    BUTTON_TEXT.STATUS.RECOVERY_REQUEST.COMPLETE,
  ],

  COLLECTION_STATUS: [
    SELECT_OPTION.DEFAULT,
    BUTTON_TEXT.STATUS.COLLECTION_REQUEST.REQUEST,
    BUTTON_TEXT.STATUS.COLLECTION_REQUEST.DISPATCH,
    BUTTON_TEXT.STATUS.COLLECTION_REQUEST.COLLECTION,
    BUTTON_TEXT.STATUS.COLLECTION_REQUEST.COMPLETE,
    BUTTON_TEXT.STATUS.COLLECTION_REQUEST.CENTER_IN,
    BUTTON_TEXT.STATUS.COLLECTION_REQUEST.CENTER_OUT,
  ],

  SHIPPER_LIST: [
    SELECT_OPTION.DEFAULT,
    '쿠팡',
    '한진택배',
    '롯데택배',
    '대한통운',
  ],

  RECALL_TYPE: [
    SELECT_OPTION.DEFAULT,
    SELECT_OPTION.RECOVERY_ROUND.RECALL_TYPE.RETURN_ORDER,
    SELECT_OPTION.RECOVERY_ROUND.RECALL_TYPE.FRESH_BAG,
  ],
};
